import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import brain_comp from "../assets/3d/brain_comp.glb";

const BrainComp = (props) => {
  const { nodes, materials } = useGLTF(brain_comp);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.327}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.521, 0.831, 1.266]}>
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials["Materil.021"]}
            />
            <mesh
              geometry={nodes.Object_41_1.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_41_2.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Object_41_3.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Object_41_4.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_41_5.geometry}
              material={materials["Materil.002"]}
            />
            <mesh
              geometry={nodes.Object_41_6.geometry}
              material={materials["Materil.003"]}
            />
            <mesh
              geometry={nodes.Object_41_7.geometry}
              material={materials["Materil.005"]}
            />
            <mesh
              geometry={nodes.Object_41_8.geometry}
              material={materials["Materil.008"]}
            />
            <mesh
              geometry={nodes.Object_41_9.geometry}
              material={materials["Materil.006"]}
            />
            <mesh
              geometry={nodes.Object_41_10.geometry}
              material={materials["Materil.007"]}
            />
            <mesh
              geometry={nodes.Object_41_11.geometry}
              material={materials["Materil.015"]}
            />
            <mesh
              geometry={nodes.Object_41_12.geometry}
              material={materials["Materil.009"]}
            />
            <mesh
              geometry={nodes.Object_41_13.geometry}
              material={materials["Materil.012"]}
            />
            <mesh
              geometry={nodes.Object_41_14.geometry}
              material={materials["Materil.011"]}
            />
            <mesh
              geometry={nodes.Object_41_15.geometry}
              material={materials["Materil.013"]}
            />
            <mesh
              geometry={nodes.Object_41_16.geometry}
              material={materials["Materil.016"]}
            />
            <mesh
              geometry={nodes.Object_41_17.geometry}
              material={materials["Materil.014"]}
            />
            <mesh
              geometry={nodes.Object_41_18.geometry}
              material={materials["Materil.018"]}
            />
            <mesh
              geometry={nodes.Object_41_19.geometry}
              material={materials["Materil.019"]}
            />
            <mesh
              geometry={nodes.Object_41_20.geometry}
              material={materials["Materil.020"]}
            />
            <mesh
              geometry={nodes.Object_41_21.geometry}
              material={materials["Materil.022"]}
            />
            <mesh
              geometry={nodes.Object_41_22.geometry}
              material={materials["Materil.023"]}
            />
            <mesh
              geometry={nodes.Object_41_23.geometry}
              material={materials["Materil.010"]}
            />
            <mesh
              geometry={nodes.Object_41_24.geometry}
              material={materials["Materil.017"]}
            />
            <mesh
              geometry={nodes.Object_41_25.geometry}
              material={materials["Materil.024"]}
            />
            <mesh
              geometry={nodes.Object_41_26.geometry}
              material={materials["Materil.025"]}
            />
            <mesh
              geometry={nodes.Object_41_27.geometry}
              material={materials["Materil.035"]}
            />
            <mesh
              geometry={nodes.Object_41_28.geometry}
              material={materials["Materil.036"]}
            />
            <mesh
              geometry={nodes.Object_41_29.geometry}
              material={materials["Materil.040"]}
            />
            <mesh
              geometry={nodes.Object_41_30.geometry}
              material={materials["Materil.041"]}
            />
            <mesh
              geometry={nodes.Object_41_31.geometry}
              material={materials["Materil.029"]}
            />
            <mesh
              geometry={nodes.Object_41_32.geometry}
              material={materials["Materil.031"]}
            />
            <mesh
              geometry={nodes.Object_41_33.geometry}
              material={materials["Materil.042"]}
            />
            <mesh
              geometry={nodes.Object_41_34.geometry}
              material={materials["Materil.044"]}
            />
            <mesh
              geometry={nodes.Object_41_35.geometry}
              material={materials["Materil.045"]}
            />
            <mesh
              geometry={nodes.Object_41_36.geometry}
              material={materials["Materil.054"]}
            />
            <mesh
              geometry={nodes.Object_41_37.geometry}
              material={materials["Materil.055"]}
            />
            <mesh
              geometry={nodes.Object_41_38.geometry}
              material={materials["Materil.070"]}
            />
            <mesh
              geometry={nodes.Object_41_39.geometry}
              material={materials["Materil.071"]}
            />
            <mesh
              geometry={nodes.Object_41_40.geometry}
              material={materials["Materil.072"]}
            />
            <mesh
              geometry={nodes.Object_41_41.geometry}
              material={materials["Materil.073"]}
            />
            <mesh
              geometry={nodes.Object_41_42.geometry}
              material={materials["Materil.074"]}
            />
            <mesh
              geometry={nodes.Object_41_43.geometry}
              material={materials["Materil.075"]}
            />
            <mesh
              geometry={nodes.Object_41_44.geometry}
              material={materials["Materil.076"]}
            />
            <mesh
              geometry={nodes.Object_41_45.geometry}
              material={materials["Materil.077"]}
            />
            <mesh
              geometry={nodes.Object_41_46.geometry}
              material={materials["Materil.078"]}
            />
            <mesh
              geometry={nodes.Object_41_47.geometry}
              material={materials["Materil.079"]}
            />
            <mesh
              geometry={nodes.Object_41_48.geometry}
              material={materials["Materil.080"]}
            />
            <mesh
              geometry={nodes.Object_41_49.geometry}
              material={materials["Materil.081"]}
            />
            <mesh
              geometry={nodes.Object_41_50.geometry}
              material={materials["Materil.082"]}
            />
            <mesh
              geometry={nodes.Object_41_51.geometry}
              material={materials["Materil.083"]}
            />
            <mesh
              geometry={nodes.Object_41_52.geometry}
              material={materials["Materil.084"]}
            />
            <mesh
              geometry={nodes.Object_41_53.geometry}
              material={materials["Materil.085"]}
            />
            <mesh
              geometry={nodes.Object_41_54.geometry}
              material={materials["Materil.086"]}
            />
            <mesh
              geometry={nodes.Object_41_55.geometry}
              material={materials["Materil.087"]}
            />
            <mesh
              geometry={nodes.Object_41_56.geometry}
              material={materials["Materil.088"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default BrainComp;