/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gnossiennes (https://sketchfab.com/Gnossiennes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/compass-380bd555fe364b03a828d3f5fbf41bfa
Title: compass
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import compass from "../assets/3d/compass.glb";

const Compass = (props) => {
  const { nodes, materials } = useGLTF(compass);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.compass} />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.environment}
        />
      </group>
    </group>
  );
};

export default Compass;