/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import hobbies from "../assets/3d/hobbies.glb";

const Hobbies = (props) => {
  const { nodes, materials } = useGLTF(hobbies);
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.163, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.139}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.632, 0.254, -0.067]}>
            <mesh
              geometry={nodes.defaultMaterial002.geometry}
              material={materials.defaultMat}
            />
            <mesh
              geometry={nodes.defaultMaterial002_1.geometry}
              material={materials["Volleyball.002"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_2.geometry}
              material={materials["material.002"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_3.geometry}
              material={materials["Mtl1.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_4.geometry}
              material={materials["Mtl2.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_5.geometry}
              material={materials["Mtl3.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_6.geometry}
              material={materials["Mtl4.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_7.geometry}
              material={materials["Mtl5.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_8.geometry}
              material={materials["Nintendo_Switch_Material.001"]}
            />
            <mesh
              geometry={nodes.defaultMaterial002_9.geometry}
              material={materials["Books.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default Hobbies;