/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JMGameDev (https://sketchfab.com/JMGameDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-basic-pokeball-9b29539199c14ddea4de7776c4d758df
Title: Pokemon Basic Pokeball
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import pokeballScene from "../assets/3d/pokeball1.glb";

// A single, reusable Pokeball component
const Pokeball = ({ isCenter, onPokeballClick, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(pokeballScene);
  const { actions } = useAnimations(animations, group);

  // Play animation when the center pokeball is clicked
  useEffect(() => {
    // The gltfjsx-generated file might not have animations, but if it does,
    // this logic finds and prepares the primary animation.
    if (animations && animations.length > 0) {
      const animationName = animations[0].name;
      // Stop all other animations and play the desired one
      actions[animationName].stop();
    }
  }, [animations, actions]);

  const handleClick = (e) => {
    e.stopPropagation(); // Prevent drag controls from firing on a click

    if (isCenter) {
      // If it's the center pokeball, play its animation.
      const animationName = animations[0]?.name;
      if (animationName && actions[animationName]) {
        actions[animationName].reset().play();
      }
    } else {
      // If a non-centered pokeball is clicked, call the passed function
      // to make it the active one.
      onPokeballClick();
    }
  };

  return (
    <group ref={group} {...props} dispose={null} onClick={handleClick}>
       {/* The following is the 3D model structure from your original file */}
      <group name="Scene">
        <group name="Sketchfab_model">
          <group name="74a458567a634d269e7923d64d27cb7dfbx">
            <group name="RootNode">
              <group name="BlackLower_Lowpoly">
                <group name="Object_13" />
              </group>
              <group name="BlackUpper_Lowpoly">
                <group name="Object_16" />
              </group>
              <group name="BodyLower_Lowpoly">
                <group name="Object_7" />
              </group>
              <group name="BodyUpper_Lowpoly">
                <group name="Object_4" />
              </group>
              <group name="Button_Lowpoly">
                <group name="Object_10" />
              </group>
              <group name="EngineLower_Lowpoly">
                <group name="Object_22" />
              </group>
              <group name="EngineUpper_Lowpoly">
                <group name="Object_19" />
              </group>
              <group name="MirrorLower_Lowpoly">
                <group name="Object_28" />
              </group>
              <group name="MirrorUpper_Lowpoly">
                <group name="Object_25" />
              </group>
              <group name="Tubes_Lowpoly">
                <group name="Object_31" />
              </group>
            </group>
          </group>
        </group>
        <group name="Empty" position={[-0.431, 0.069, -8.617]}>
          <mesh
            name="BlackLower_Lowpoly_08_-_Default_0"
            castShadow
            receiveShadow
            geometry={nodes['BlackLower_Lowpoly_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
          <mesh
            name="Button_Lowpoly_08_-_Default_0"
            castShadow
            receiveShadow
            geometry={nodes['Button_Lowpoly_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
      </group>
    </group>
  );
};

export default Pokeball;